In [1]:
import numpy as np

In [4]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
a*b

array([ 2,  6, 12, 20])

In [7]:
np.array([3.14,4,2,13])

array([ 3.14,  4.  ,  2.  , 13.  ])

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [12]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [15]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [17]:
np.arange(0,65,9)

array([ 0,  9, 18, 27, 36, 45, 54, 63])

In [18]:
np.random.normal(10,4,(3,4))

array([[ 9.00889714,  8.64788847,  7.96644379,  5.81740777],
       [12.52352048, 12.97812035, 13.312344  , 16.0908765 ],
       [-1.3733053 , 12.48362337,  7.32978779,  5.08992193]])

In [19]:
a = np.arange(1,10)

In [21]:
a.ndim

1

In [26]:
b=a.reshape((3,3))

In [27]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
b.ndim

2

In [29]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [30]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [31]:
z = np.array([7,8,9])

In [32]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
a = np.array([[1,2,3],[4,5,6]])

In [35]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [39]:
x = np.array([1,2,3,99,99,3,2,1])

In [40]:
np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [41]:
a,b,c = np.split(x , [3,5])

In [42]:
a

array([1, 2, 3])

In [43]:
b

array([99, 99])

In [44]:
c

array([3, 2, 1])

In [45]:
# İki boyutlu ayırma

In [46]:
m = np.arange(16).reshape(4,4)

In [47]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [51]:
a,b,c,d = np.split(m,(1,2,3))

In [52]:
a

array([[0, 1, 2, 3]])

In [53]:
d

array([[12, 13, 14, 15]])

In [54]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [55]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [56]:
ust , alt = np.vsplit(m,[2])

In [57]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [58]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [59]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [60]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [61]:
v = np.array([2,1,4,3,5])

In [62]:
v

array([2, 1, 4, 3, 5])

In [63]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [64]:
v

array([2, 1, 4, 3, 5])

In [72]:
m = np.random.normal(20,5,(3,3))

In [73]:
np.sort(m,axis = 1)

array([[16.29198962, 18.54017869, 22.151215  ],
       [15.10868974, 16.31002177, 17.21540952],
       [17.85593982, 19.06358285, 20.51155579]])

In [78]:
m

array([[22.151215  , 16.29198962, 18.54017869],
       [16.31002177, 15.10868974, 17.21540952],
       [20.51155579, 17.85593982, 19.06358285]])

In [80]:
np.sort(m,axis = 0)

array([[16.31002177, 15.10868974, 17.21540952],
       [20.51155579, 16.29198962, 18.54017869],
       [22.151215  , 17.85593982, 19.06358285]])

In [81]:
m.size

9

In [82]:
m.dtype

dtype('float64')

In [87]:
np.random.randint(10)

array([[2, 8, 4],
       [4, 7, 7],
       [3, 7, 4],
       [3, 9, 2],
       [9, 5, 0],
       [7, 9, 9]])

In [90]:
a=5*np.array([1,2,3,4,5,6])

In [92]:
a.ndim

1

In [94]:
a = np.random.randint(10,size = 10)

In [98]:
a[-1]

2

In [99]:
m = np.random.randint(10, size = (3,5))
m

array([[3, 2, 6, 1, 3],
       [7, 7, 7, 4, 2],
       [0, 8, 4, 5, 7]])

In [100]:
m[0,0]

3

In [101]:
m[1][1]

7

In [102]:
m[1,1]

7

In [104]:
m[1,4] = 99

In [105]:
m[1,4]

99

In [108]:
m[1,4] = 2.2

In [109]:
m

array([[3, 2, 6, 1, 3],
       [7, 7, 7, 4, 2],
       [0, 8, 4, 5, 7]])

In [110]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [111]:
a[0:3]

array([20, 21, 22])

In [112]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [113]:
a[1::2]

array([21, 23, 25, 27, 29])

In [114]:
a[0::3]

array([20, 23, 26, 29])

In [116]:
m = np.random.randint(10,size =(5,5))

In [117]:
m

array([[5, 9, 5, 8, 2],
       [1, 4, 0, 9, 3],
       [9, 1, 7, 3, 9],
       [3, 4, 6, 6, 6],
       [1, 7, 1, 1, 0]])

In [118]:
m[:,4]

array([2, 3, 9, 6, 0])

In [119]:
m[0,:]

array([5, 9, 5, 8, 2])

In [122]:
m[:2,:]

array([[5, 9, 5, 8, 2],
       [1, 4, 0, 9, 3]])

In [123]:
m[0:2 , 0:3]

array([[5, 9, 5],
       [1, 4, 0]])

In [124]:
m[:, 0:2]

array([[5, 9],
       [1, 4],
       [9, 1],
       [3, 4],
       [1, 7]])

In [125]:
a = np.random.randint(10 , size= (5,5))

In [126]:
a

array([[2, 3, 0, 0, 1],
       [0, 0, 5, 0, 1],
       [5, 1, 2, 8, 6],
       [7, 8, 7, 9, 4],
       [8, 7, 5, 2, 1]])

In [127]:
alt_a = a[0:3,0:2]

In [128]:
alt_a

array([[2, 3],
       [0, 0],
       [5, 1]])

In [129]:
m = np.random.randint(10,size =(5,5))
m

array([[1, 3, 6, 1, 7],
       [7, 3, 9, 3, 5],
       [5, 3, 1, 5, 3],
       [8, 5, 4, 0, 9],
       [6, 3, 7, 5, 8]])

In [130]:
alt_b = m[0:3 , 0:3].copy()

In [131]:
alt_b

array([[1, 3, 6],
       [7, 3, 9],
       [5, 3, 1]])

In [133]:
alt_b

array([[1, 3, 6],
       [7, 3, 9],
       [5, 3, 1]])

In [134]:
m

array([[1, 3, 6, 1, 7],
       [7, 3, 9, 3, 5],
       [5, 3, 1, 5, 3],
       [8, 5, 4, 0, 9],
       [6, 3, 7, 5, 8]])

In [135]:
alt_b*3

array([[ 3,  9, 18],
       [21,  9, 27],
       [15,  9,  3]])

In [136]:
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [137]:
v[1]

3

In [138]:
#fancyIndex
al_getir = [1,3,5]

In [142]:
v[al_getir]

array([ 3,  9, 15])

In [151]:
m = np.arange(9).reshape((3,3))

In [152]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [149]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [159]:
m[satir,sutun]

array([1, 5])

In [160]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [164]:
m[0,[1,2]]

array([1, 2])

In [165]:
m[:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [166]:
v = np.array([1,2,3,4,5])

In [167]:
v > 5

array([False, False, False, False, False])

In [168]:
v[v>3]

array([4, 5])

In [169]:
v * 2

array([ 2,  4,  6,  8, 10])

In [170]:
v * 5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [179]:
a = np.array([[5,1],
             [1,3]])
b = np.array([12,10])

In [180]:
x = np.linalg.solve(a,b)

In [181]:
x

array([1.85714286, 2.71428571])