In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
b = np.array([5,4,9,8,4])

In [3]:
a*b

array([ 5,  8, 27, 32, 20])

In [4]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.full((6,4),8)

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [10]:
np.arange(3,98,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96])

In [11]:
np.linspace(3,98,3)

array([ 3. , 50.5, 98. ])

In [17]:
np.random.normal(10,4)

12.411426068307765

In [19]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
a = np.arange(1,10)

In [21]:
a.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [42]:
a = np.concatenate((x,y))

In [44]:
a = np.array([[1,2,3]
             ,[4,5,6]])

In [46]:
np.concatenate((a,a),axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [47]:
a.ndim

2

In [48]:
aray = np.array([2,2,2,6666666,6666666,365235])

In [51]:
a,b,c=np.split(aray,(2,5))

In [54]:
a = np.arange(1,17).reshape((4,4))

In [55]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [57]:
np.vsplit(a,[2])

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [58]:
np.hsplit(a,[2])

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [71]:
v=np.random.randint(0,1100,10)

In [72]:
np.sort(v)

array([ 33, 160, 224, 276, 506, 549, 652, 670, 681, 716])

In [74]:
a=np.random.normal(10,5,(4,4))

In [80]:
a

array([[ 9.34773747,  1.35489677, 16.41785538, 14.74061534],
       [ 6.63785676,  3.94744236, 12.91494019, 13.51753588],
       [ 6.04369549, 11.95238944,  7.41740857,  4.40331587],
       [10.15761433, 10.19670642,  9.08065196, 10.71187076]])

In [81]:
np.sort(a,axis=0)

array([[ 6.04369549,  1.35489677,  7.41740857,  4.40331587],
       [ 6.63785676,  3.94744236,  9.08065196, 10.71187076],
       [ 9.34773747, 10.19670642, 12.91494019, 13.51753588],
       [10.15761433, 11.95238944, 16.41785538, 14.74061534]])